[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run db:generate"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"

# MySQL Database Configuration
MYSQL_DATABASE = "railway"
MYSQL_USER = "root"
MYSQL_ROOT_PASSWORD = "rFGqmfUlVUcBHwqXviwmqhRazfdNjAXX"
MYSQL_HOST = "${RAILWAY_PRIVATE_DOMAIN}"
MYSQL_PORT = "3306"
DATABASE_URL = "mysql://${MYSQL_USER}:${MYSQL_ROOT_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}"
